### ISSUE TITLE
Ability to obtain auth session in /callback

### ISSUE THREAD

**Issue by dxptqhtlutehvlyxcmtg** [kinde-oss/kinde-remix-sdk#11]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

While responding to `/kinde-auth/callback` we need to take care of "new user" stuff prior to redirection, if we haven't seen the particular user before. Currently, we can't do this because there doesn't seem to be a way to obtain the user session in the callback route.

### What solution would you like to see?

Using the plain `@kinde-oss/kinde-typescript-sdk` in Node,  and our own implementation of a db backed session store, we are able to obtain a user in the callback route immediately after calling `handleRedirectToApp`. For example:

```typescript
// client is instance from createKindeServerClient()
await client.handleRedirectToApp(sessionManager, url);

// userProfile is obtained
const userProfile = await client.getUserProfile(sessionManager);
```

However, it's not possible to do something similar with the Remix SDK:
```typescript
import { handleAuth, getKindeSession } from '@kinde-oss/kinde-remix-sdk';
import type { LoaderFunctionArgs } from '@remix-run/node';

export async function loader({ params, request }: LoaderFunctionArgs) {
  if(params.index === 'callback') {

    await handleAuth(request, params.index);
  
    const session = await getKindeSession(request);
    
    // will be null
    const userProfile = await session.getUserProfile();

    // will be false
    const isAuthenticated = await session.isAuthenticated();
```

Most apps need to configure new users upon successful registration and there's not really another place for that then in the callback route. We'd like a way to obtain the newly logged in user during the response to that route.

**Comment by peterphanouvong** [comment]
We can handle calling a function after authentication with `onRedirectCallback` (added in v1.1.1) - see more in the [docs](https://docs.kinde.com/developer-tools/sdks/backend/remix-sdk/#call-a-function-after-authentication)
