### ISSUE TITLE
Bug: `user` is `undefined` in `onRedirectCallback`.

### ISSUE THREAD

**Issue by chopfitzroy** [kinde-oss/kinde-remix-sdk#19]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

Issue previously discussed here: https://discord.com/channels/1070212618549219328/1281552214330048554
Reproducible example created here: https://github.com/chopfitzroy/kinde-example/tree/master (instructions in README)

Essentially when trying to use the `onRedirectCallback` to sync up my Convex database with the Kinde user the `user` is `undefined` in the callback.

### Library URL

https://github.com/kinde-oss/kinde-remix-sdk

### Library version

1.1.2

### Operating system(s)

macOS

### Operating system version(s)

14.5 (23F79)

### Further environment details

Also seeing this on WSL 2 on Windows 11 machine.

### Reproducible test case URL

https://github.com/chopfitzroy/kinde-example/tree/master

**Comment by peterphanouvong** [comment]
Hey @chopfitzroy thanks for raising this, this is the same as #17 

I have just released a beta version `v1.1.3-beta.2` which seems to have fixed it. 

The fix is also in a PR to main :)

**Comment by peterphanouvong** [comment]
Should now be fixed in v1.1.3 https://www.npmjs.com/package/@kinde-oss/kinde-remix-sdk/v/1.1.3
